# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-01-25'
previous_iteration_name: Iteration 72
last_updated: '2026-01-21T21:59:11.861742-05:00'
_timezone_note: All dates are in EST (Eastern Time)
