# Iteration Schedule - All dates in EDT (Eastern Time)
next_iteration_start_date: '2026-09-06'
previous_iteration_name: Iteration 88
last_updated: '2026-08-25T10:33:23.438075-04:00'
_timezone_note: All dates are in EDT (Eastern Time)
