# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-02-22'
previous_iteration_name: Iteration 74
last_updated: '2026-02-18T22:31:21.839466-05:00'
_timezone_note: All dates are in EST (Eastern Time)
