# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2025-12-28'
previous_iteration_name: Iteration 70
last_updated: '2025-12-22T21:48:55.936510-05:00'
_timezone_note: All dates are in EST (Eastern Time)
