# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-01-11'
previous_iteration_name: Iteration 71
last_updated: '2026-01-07T21:51:43.361051-05:00'
_timezone_note: All dates are in EST (Eastern Time)
