# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-01-25'
previous_iteration_name: Iteration 72
last_updated: '2026-01-25T00:29:54.079342-05:00'
_timezone_note: All dates are in EST (Eastern Time)
