# Iteration Schedule - All dates in EDT (Eastern Time)
next_iteration_start_date: '2026-04-19'
previous_iteration_name: Iteration 78
last_updated: '2026-04-16T23:57:58.954640-04:00'
_timezone_note: All dates are in EDT (Eastern Time)
