# Iteration Schedule - All dates in EDT (Eastern Time)
next_iteration_start_date: '2026-07-26'
previous_iteration_name: Iteration 85
last_updated: '2026-07-24T23:56:35.673835-04:00'
_timezone_note: All dates are in EDT (Eastern Time)
