# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-02-08'
previous_iteration_name: Iteration 73
last_updated: '2026-02-01T22:34:54.250008-05:00'
_timezone_note: All dates are in EST (Eastern Time)
