# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-01-11'
previous_iteration_name: Iteration 71
last_updated: '2026-01-10T22:02:56.775254-05:00'
_timezone_note: All dates are in EST (Eastern Time)
