# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-02-22'
previous_iteration_name: Iteration 74
last_updated: '2026-02-15T22:34:59.234967-05:00'
_timezone_note: All dates are in EST (Eastern Time)
