# Iteration Schedule - All dates in EST (Eastern Time)
next_iteration_start_date: '2026-02-08'
previous_iteration_name: Iteration 73
last_updated: '2026-02-08T01:02:30.739055-05:00'
_timezone_note: All dates are in EST (Eastern Time)
