#!/bin/bash
# Auto-commit published reports
# Run this after publishing reports or set up as a cron job

cd "$(dirname "$0")"

# Check if there are any changes in docs/ or reports/
if [ -n "$(git status --porcelain docs/ reports/)" ]; then
    echo "📝 Found new reports, committing..."
    
    git add docs/ reports/
    git commit -m "Auto-publish report $(date +'%Y-%m-%d %H:%M %Z')

Generated by automated report publisher"
    
    # Push to current branch
    CURRENT_BRANCH=$(git branch --show-current)
    git push origin "$CURRENT_BRANCH"
    
    echo "✅ Reports committed and pushed to $CURRENT_BRANCH"
else
    echo "ℹ️  No new reports to commit"
fi
